### ISSUE TITLE
How does containers start in MyliquibasePlanetApplicationTests? 

### ISSUE THREAD

**Issue by akuzni2** [mydeveloperplanet/myliquibaseplanet#1]
Hi - first off this is a great example and I really enjoyed your blog post. I'm stuck though at figuring out how the containers get started in `MyliquibasePlanetApplicationTests`. I notice that the class is annotated with `@Testcontainers` however I don't see any declarations of `@Container` as mentioned in the [testcontainers documentation](https://www.testcontainers.org/test_framework_integration/junit_5/). Just wondering if you could explain this? I know it's not really an issue but not sure how else to reach out about it. Thank you.

**Comment by mydeveloperplanet** [comment]
Hi there,

thank you for the compliment, it is always nice to get some response.

Now to your question: I am not quite sure, but as far as I understand it, the @TestContainers annotation will create a container for you based on the settings in the bootstrap-test.properties. When you want to create your own instance of a container, it is also possible to create one within your test with the @Container annotation. But you will only need this when you need the instance in your test. In the testcontainers documentation, the postgresqlContainer is also not a static container (it will be started and stopped per method) and some specific properties are set and in a test it is checked whether the database is running. Similar for the MySqlContainer in the documentation, only this one is only once started and stopped for the test, just like the default one when you do not add an instance with the @Container annotation.
In our example, we do not need a handle to the container instance and therefore it is not needed to add it.

I hope this helps.

Best regards,
Gunter
________________________________
Van: akuzni2 <notifications@github.com>
Verzonden: donderdag 11 juni 2020 6:37
Aan: mydeveloperplanet/myliquibaseplanet <myliquibaseplanet@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [mydeveloperplanet/myliquibaseplanet] How does containers start in MyliquibasePlanetApplicationTests? (#1)


Hi - first off this is a great example and I really enjoyed your blog post. I'm stuck though at figuring out how the containers get started in MyliquibasePlanetApplicationTests. I notice that the class is annotated with @Testcontainers however I don't see any declarations of @Container as mentioned in the testcontainers documentation<https://www.testcontainers.org/test_framework_integration/junit_5/>. Just wondering if you could explain this? I know it's not really an issue but not sure how else to reach out about it. Thank you.

**Comment by akuzni2** [comment]
Ok I think that makes sense. I'll have to do a bit more research on this thanks for the explanation
